[template]
cargo_generate_version = ">=0.9.0"

[hooks]
pre = ["cargo-generate/remove_rprs.rhai"]

[placeholders]
flash_method = { prompt = "Which flashing method do you intend to use?", choices = [
  "probe-rs",
  "elf2uf2-rs",
  "custom",
  "none"
], default = "probe-rs", type = "string" }

[conditional.'flash_method == "custom"'.placeholders]
flash_method_custom = { prompt = "Enter the runner command to use", type = "string" }
